apiVersion: v1
kind: Namespace
metadata:
  name: jatin
--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app
  namespace: jatin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
        - name: nodejs
          image: jatinbhalla1991/nodejs-hello-world:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: node-app-service
  namespace: jatin
spec:
  selector:
    app: node-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
