version: "3.9"
services:
  web:
   image: nginx:alpine
   container_name: nginx_static
   ports:
    - "8080:80"
   restart: unless-stopped
  
  backend:
    image: mysql
    container_name: mysql
    ports:
     - "3307:3306"
    environment:
     MYSQL_ROOT_PASSWORD: root
     MYSQL_DATABASE: appdb
     MYSQL_USER: appuser
     MYSQL_PASSWORD: password@123