name: Run Selenium Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Set up Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Display Chrome version
        run: google-chrome --version

      - name: Start Xvfb
        run: |
          export DISPLAY=:99
          Xvfb :99 -screen 0 1920x1080x24 > /dev/null 2>&1 &

      - name: Build and run tests with Maven
        run: mvn test
        working-directory: ./selenium-maven-project
        env:
          DISPLAY: :99
      - name: Build Maven packages if tests pass
        run: mvn package
        working-directory: ./selenium-maven-project
        if: success()